# Configuration file for the script 'Demo_train_nn.py'

DATA:
    N: 512
    srate: 0.25
    path_data: '/mn/nam-shub-01/scratch/vegarant/ellipses'
    path_pattern: '/mn/sarpanitu/ansatte-u4/vegarant/storage_firenet/samp_patt'

MODEL:
    dest_model: 'models'
    model_nbr: 5

TRAIN:
    epochs: 50
    batch_size: 5
    train_size: 5000
    val_size: 50
    test_size: 4
    intensity_diff: null
    add_noise: no
    noise_level: 10
    shuffle: yes

NETWORK:
    use_bias: yes
    kernel_size: (3,3)
    init_features: 32

COMPUTER_SETUP:
    use_gpu: yes
    dtype:   'tf.float32'
    cdtype:  'tf.complex64'
    compute_node: 1


