# Configuration file for the script 'Demo_train_nn.py'

DATA:
    N: 512
    srate: 0.12
    path_data: '/itf-fi-ml/home/vegarant/storage/ellipses'
    path_pattern: '/itf-fi-ml/home/vegarant/storage/samp_patt'

MODEL:
    dest_model: 'models'
    model_nbr: 105

TRAIN:
    epochs: 101
    batch_size: 10
    train_size: 5000
    val_size: 50
    test_size: 4
    intensity_diff: 30 
    add_noise: no
    noise_level: 10
    shuffle: yes

NETWORK:
    use_bias: yes
    kernel_size: (3,3)
    init_features: 32

COMPUTER_SETUP:
    use_gpu: yes
    dtype:   'tf.float32'
    cdtype:  'tf.complex64'
    compute_node: 4


